package com.project.back_end.models;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.JoinColumn;
import java.time.LocalDateTime;

/**
 * Represents an appointment within the Smart Clinic Management System.
 *
 * <p>This entity stores all scheduling information for a patient’s
 * appointment with a doctor, including date, time, and appointment notes.</p>
 */
@Entity
public class Appointment {

    /**
     * The unique identifier for the appointment.
     * This value is automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The doctor assigned to this appointment.
     * Many appointments can belong to one doctor.
     */
    @ManyToOne
    @JoinColumn(name = "doctor_id", nullable = false)
    private Doctor doctor;

    /**
     * The patient attending the appointment.
     * Many appointments can belong to one patient.
     */
    @ManyToOne
    @JoinColumn(name = "patient_id", nullable = false)
    private Patient patient;

    /**
     * The date and time when the appointment is scheduled.
     */
    private LocalDateTime appointmentDateTime;

    /**
     * Additional notes or description for the appointment.
     */
    private String notes;

    /** Default constructor required by JPA. */
    public Appointment() {
    }

    // -------------------------
    // Getters and Setters
    // -------------------------

    /**
     * Returns the unique identifier of the appointment.
     *
     * @return the appointment ID
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the appointment ID.
     *
     * @param id the unique identifier
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Returns the doctor for this appointment.
     *
     * @return the doctor entity
     */
    public Doctor getDoctor() {
        return doctor;
    }

    /**
     * Sets the doctor assigned to this appointment.
     *
     * @param doctor the doctor entity
     */
    public void setDoctor(Doctor doctor) {
        this.doctor = doctor;
    }

    /**
     * Returns the patient attending this appointment.
     *
     * @return the patient entity
     */
    public Patient getPatient() {
        return patient;
    }

    /**
     * Sets the patient for this appointment.
     *
     * @param patient the patient entity
     */
    public void setPatient(Patient patient) {
        this.patient = patient;
    }

    /**
     * Returns the scheduled date and time of the appointment.
     *
     * @return the appointment date-time
     */
    public LocalDateTime getAppointmentDateTime() {
        return appointmentDateTime;
    }

    /**
     * Sets the scheduled date and time for the appointment.
     *
     * @param appointmentDateTime the date-time value
     */
    public void setAppointmentDateTime(LocalDateTime appointmentDateTime) {
        this.appointmentDateTime = appointmentDateTime;
    }

    /**
     * Returns any notes associated with the appointment.
     *
     * @return the appointment notes
     */
    public String getNotes() {
        return notes;
    }

    /**
     * Sets any notes for this appointment.
     *
     * @param notes the text notes
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }
}
