package com.project.back_end.models;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;

/**
 * Represents a doctor in the Smart Clinic Management System.
 * 
 * <p>This entity is stored in the database and contains identifying
 * and descriptive information about each doctor within the clinic.</p>
 */
@Entity
public class Doctor {

    /**
     * The unique identifier for the doctor.
     * This value is automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** The doctor's first name. */
    private String firstName;

    /** The doctor's last name. */
    private String lastName;

    /** The medical specialty of the doctor (e.g., Pediatrics, Dermatology). */
    private String specialty;

    /** The email address used for clinic communication. */
    private String email;

    /** The phone number for contacting the doctor. */
    private String phoneNumber;

    /** Default constructor required by JPA. */
    public Doctor() {
    }

    // -------------------------
    // Getters and Setters
    // -------------------------

    /**
     * Returns the unique identifier of the doctor.
     *
     * @return the doctor ID
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the doctor’s ID.
     *
     * @param id the unique identifier
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Returns the doctor’s first name.
     *
     * @return the first name
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the doctor’s first name.
     *
     * @param firstName the first name
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * Returns the doctor’s last name.
     *
     * @return the last name
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the doctor’s last name.
     *
     * @param lastName the last name
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * Returns the doctor's medical specialty.
     *
     * @return the specialty
     */
    public String getSpecialty() {
        return specialty;
    }

    /**
     * Sets the doctor’s medical specialty.
     *
     * @param specialty the specialty name
     */
    public void setSpecialty(String specialty) {
        this.specialty = specialty;
    }

    /**
     * Returns the email address of the doctor.
     *
     * @return the email address
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the doctor’s email address.
     *
     * @param email the email address
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Returns the doctor's phone number.
     *
     * @return the phone number
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * Sets the doctor’s phone number.
     *
     * @param phoneNumber the contact number
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
}
